apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pg-cloudnative-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: pg-operator
  sources:
    - repoURL: 'git@github.com:sebastiaankok/k8s-homelab.git'
      targetRevision: main
      ref: values
    - repoURL: 'git@github.com:sebastiaankok/k8s-homelab.git'
      targetRevision: main
      path: "clusters/k8s-home/argocd/apps/databases/pg-cloudnative-operator/"
      directory:
        exclude: '{application.yaml,values.yaml}'
    - chart: cloudnative-pg
      repoURL: 'https://cloudnative-pg.io/charts/'
      targetRevision: 0.21.5
      helm:
        releaseName: "cloudnative-pg"
        valueFiles:
          - $values/clusters/k8s-home/argocd/apps/databases/pg-cloudnative-operator/values.yaml
