apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich
  namespace: postgresql
spec:
  name: immich
  owner: immich
  cluster:
    name: postgresql-17
  extensions:
  - name: vector
  - name: vchord
  - name: cube
  - name: earthdistance
---
