---
nameOverride: &name gha-runner-scale-set-home-ops
runnerScaleSetName: gha-runner-scale-set-home-ops
githubConfigUrl: https://github.com/sebastiaankok/home-ops
githubConfigSecret: pre-defined-secret
minRunners: 1
maxRunners: 10
containerMode:
  type: kubernetes
  kubernetesModeWorkVolumeClaim:
    accessModes:
      - ReadWriteOnce
    storageClassName: local-path
    resources:
      requests:
        storage: 25Gi
controllerServiceAccount:
  name: actions-runner-controller
  namespace: arc-systems
template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/sebastiaankok/home-ops/ci-image:f957f6cc
        command:
          - /home/runner/run.sh
        env:
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
          - name: NODE
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        # volumeMounts:
        #   - mountPath: /var/run/secrets/talos.dev
        #     name: talos
        #     readOnly: true
    # volumes:
    #   - name: talos
    #     secret:
    #       secretName: *name
