apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
  name: jellyseerr-external
  namespace: media
spec:
  ingressClassName: ingress-nginx-media
  rules:
  - host: hub.otohgunga.nl
    http:
      paths:
      - backend:
          service:
            name: jellyseerr
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - hub.otohgunga.nl
    secretName: hub-https-tls
