apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
  name: jellyfin-external
  namespace: media
spec:
  ingressClassName: ingress-nginx-media
  rules:
  - host: tv.otohgunga.nl
    http:
      paths:
      - backend:
          service:
            name: jellyfin
            port:
              number: 8096
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - tv.otohgunga.nl
    secretName: tv-https-tls
