controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/prowlarr-nightly
          tag: 1.17.1.4483@sha256:10238c391b6b765b1479ef2a5520bf37e1c7e7cb02d3fb59e9b576d58cf6236c
        env:
          PROWLARR__INSTANCE_NAME: Prowlarr
          PROWLARR__PORT: &port 9696
          PROWLARR__LOG_LEVEL: info
          PROWLARR__ANALYTICS_ENABLED: "False"
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - ALL
      dnsdist:
        image:
          repository: docker.io/powerdns/dnsdist-18
          tag: 1.8.3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
      gluetun:
        image:
          repository: ghcr.io/qdm12/gluetun
          tag: latest@sha256:0996fa99fd56b156f7f3afd9051ca1b7b770814806fef3d4cccf962e75e920a0
        env:
          - name: VPN_SERVICE_PROVIDER
            value: protonvpn
          - name: SERVER_COUNTRIES
            value: Netherlands
          - name: DNS_PLAINTEXT_ADDRESS
            value: 127.0.0.2
          - name: SHADOWSOCKS
            value: "on"
          - name: DOT
            value: "off"
          - name: FREE_ONLY
            value: "on"
          - name: FIREWALL_OUTBOUND_SUBNETS
            value: 10.0.0.0/16,10.42.0.0/16,10.43.0.0/16
          - name: FIREWALL_INPUT_PORTS
            value: *port
        envFrom:
          - secretRef:
              name: vpn-secret
        securityContext:
          capabilities:
            add:
              - NET_ADMIN

persistence:
  config:
    enabled: true
    existingClaim: hostpath-prowlarr-pvc
    advancedMounts:
      main:
        main:
          - path: /config
  gluetun-data:
    type: emptyDir
    advancedMounts:
      main:
        gluetun:
          - path: /tmp/gluetun
  dnsdist-config:
    type: configMap
    name: dnsdist-config
    advancedMounts:
      main:
        dnsdist:
          - path: /etc/dnsdist/dnsdist.conf
            subPath: dnsdist.conf
            readOnly: true

service:
  main:
    ports:
      http:
        port: *port

ingress:
  main:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
    hosts:
      - host: "prowlarr.otohgunga.nl"
        paths:
          - path: /
            service:
              name: main
              port: http
    tls:
      - hosts:
          - "prowlarr.otohgunga.nl"
        secretName: "prowlarr-otohgunga-tls"
