apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-sabnzbd-pv
  labels:
    app.kubernetes.io/name: sabnzbd
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local-sabnzbd
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/data/mediaserver/sabnzbd"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-home
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-sabnzbd-pvc
  namespace: media
  labels:
    app.kubernetes.io/name: sabnzbd
spec:
  storageClassName: local-sabnzbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
