apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-wyoming-whisper-pv
  namespace: hass
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: hostpath-wyoming-whisper
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/hass/wyoming-whisper"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-wyoming-whisper-pvc
  namespace: hass
spec:
  storageClassName: hostpath-wyoming-whisper
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
