---
extends: default

rules:
  document-start:
    level: warning

  indentation:
    spaces: 2
    indent-sequences: true
    level: warning

  line-length:
    max: 500

  truthy:
    level: warning

  comments:
    min-spaces-from-content: 1

  comments-indentation: disable

  empty-lines:
    level: error

  braces:
    level: warning

  new-line-at-end-of-file:
    level: warning