controllers:
  main:
    pod:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/tautulli
          tag: 2.13.4@sha256:633a57b2f8634feb67811064ec3fa52f40a70641be927fdfda6f5d91ebbd5d73
        resources:
          requests:
            cpu: 5m
            memory: 128Mi
          limits:
            memory: 512Mi

service:
  main:
    controller: main
    ports:
      http:
        port: 8181

ingress:
  main:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
    hosts:
      - host: "tautulli.otohgunga.nl"
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - "tautulli.otohgunga.nl"
        secretName: "tautulli-otohgunga-tls"

persistence:
  config:
    enabled: true
    existingClaim: hostpath-tautulli-pvc
    globalMounts:
      - path: /config


