controllers:
  main:
    pod:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/tautulli
          tag: 2.13.4@sha256:b3000c0063cc4c0c6f2436fb7174f4bcfd8d91eca05206731edccb8b643ea570
        resources:
          requests:
            cpu: 5m
            memory: 128Mi
          limits:
            memory: 512Mi

service:
  main:
    ports:
      http:
        port: 8181

ingress:
  main:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
    hosts:
      - host: "tautulli.example.com"
        paths:
          - path: /
            service:
              name: main
              port: http
    tls:
      - hosts:
          - "tautulli.example.com"
        secretName: "tautulli-otohgunga-tls"

persistence:
  config:
    enabled: true
    existingClaim: hostpath-tautulli-pvc
    globalMounts:
      - path: /config


