controllers:
  main:
    pod:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/tautulli
          tag: 2.15.0@sha256:189f7b29da755a8e20da45af1e56bc9fc88d836a363da4273a52b267609511c4
        resources:
          requests:
            cpu: 5m
            memory: 128Mi
          limits:
            memory: 512Mi

service:
  main:
    controller: main
    ports:
      http:
        port: 8181

ingress:
  main:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
    hosts:
      - host: "tautulli.example.com"
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - "tautulli.example.com"
        secretName: "tautulli-https-tls"

persistence:
  config:
    enabled: true
    existingClaim: hostpath-tautulli-pvc
    globalMounts:
      - path: /config


