deployNodeAgent: true

configuration:
  provider: aws

  # BackupStorageLocation pointing to B2
  backupStorageLocations:
    - name: b2
      provider: aws
      default: true
      bucket: nixos-homelab
      config:
        region: eu-central-003
        s3Url: https://s3.eu-central-003.backblazeb2.com/
        s3ForcePathStyle: "true"

# Credentials secret
credentials:
  existingSecret: velero-b2-credentials
