---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  ignoreDifferences:
    - group: "*"
      kind: Secret
      name: cilium-ca
      jsonPointers:
        - /data/ca.crt
        - /data/ca.key
    - group: "*"
      kind: Secret
      name: hubble-relay-client-certs
      jsonPointers:
        - /data/ca.crt
        - /data/tls.key
        - /data/tls.crt
    - group: "*"
      kind: Secret
      name: hubble-server-certs
      jsonPointers:
        - /data/ca.crt
        - /data/tls.key
        - /data/tls.crt
  destination:
    name: in-cluster
    namespace: kube-system
  sources:
    - repoURL: 'https://github.com/sebastiaankok/k8s-homelab.git'
      targetRevision: main
      ref: values
      path: "k8s/k3s-home/argocd/system/cilium/"
      directory:
        exclude: '{application.yaml,values.yaml}'
    - chart: cilium
      repoURL: 'https://helm.cilium.io/'
      targetRevision: 1.19.3
      helm:
        releaseName: "cilium"
        valueFiles:
          - $values/k8s/k3s-home/argocd/system/cilium/values.yaml
