controllers:
  main:
    annotations:
      reloader.stakater.com/auto: "true"
      backup.velero.io/backup-volumes: data
    containers:
      main:
        image:
          repository: koenkk/zigbee2mqtt
          tag: 2.6.0
        env:
          TZ: UTC
          ZIGBEE2MQTT_DATA: /data
        securityContext:
          privileged: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            memory: 512Mi

service:
  main:
    controller: main
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
    hosts:
      - host: zigbee2mqtt.example.com
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - secretName: zigbee2mqtt-https-tls
        hosts:
          - zigbee2mqtt.example.com

persistence:
  data:
    enabled: true
    #accessMode: ReadWriteOnce
    #size: 1Gi
    existingClaim: hostpath-zigbee2mqtt-pvc
    globalMounts:
      - path: /data
  #  config:
  #    enabled: true
  #    type: configMap
  #    name: zigbee2mqtt-config
  #    mountPath: /app/configuration.yaml
  #    subPath: configuration.yaml
