# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/library/common/values.schema.json
controllers:
  zigbee2mqtt:
    pod:
      annotations:
        backup.velero.io/backup-volumes: data
    containers:
      app:
        image:
          repository: koenkk/zigbee2mqtt
          tag: 2.6.0
        env:
          ZIGBEE2MQTT_DATA: /data
        securityContext:
          runAsUser: 1004
          runAsGroup: 1004
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            memory: 512Mi

service:
  app:
    controller: zigbee2mqtt
    ports:
      http:
        port: 8080

ingress:
  app:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
    hosts:
      - host: zigbee2mqtt.otohgunga.nl
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - secretName: zigbee2mqtt-https-tls
        hosts:
          - zigbee2mqtt.otohgunga.nl

persistence:
  data:
    enabled: true
    existingClaim: local-zigbee2mqtt-pvc
    globalMounts:
      - path: /data
