controllers:
  main:
    annotations:
      reloader.stakater.com/auto: "true"
      backup.velero.io/backup-volumes: data
    containers:
      main:
        image:
          repository: ghcr.io/koenkk/zigbee2mqtt
          tag: 1.40.1@sha256:8127ec2b6e5370eb83033e9cd7250a72bc418b4ead722eadb17c664bebd8b829
        env:
          TZ: UTC
          ZIGBEE2MQTT_DATA: /data
        securityContext:
          privileged: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            memory: 512Mi

service:
  main:
    controller: main
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
    hosts:
      - host: zigbee2mqtt.example.com
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - secretName: zigbee2mqtt-otohgunga-tls
        hosts:
          - zigbee2mqtt.example.com

persistence:
  data:
    enabled: true
    #accessMode: ReadWriteOnce
    #size: 1Gi
    existingClaim: hostpath-zigbee2mqtt-pvc
    globalMounts:
      - path: /data
  #  config:
  #    enabled: true
  #    type: configMap
  #    name: zigbee2mqtt-config
  #    mountPath: /app/configuration.yaml
  #    subPath: configuration.yaml
  usbserial:
    enabled: true
    type: hostPath
    hostPath: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_da3c386a8212ec11915520c7bd930c07-if00-port0
