apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: kube-system
  sources:
    - repoURL: 'git@github.com:sebastiaankok/k8s-homelab.git'
      targetRevision: main
      ref: values
    - repoURL: 'git@github.com:sebastiaankok/k8s-homelab.git'
      targetRevision: main
      path: "clusters/k8s-home/argocd/apps/system/metrics-server"
      directory:
        exclude: '{application.yaml,values.yaml}'
    - chart: metrics-server
      repoURL: 'https://kubernetes-sigs.github.io/metrics-server'
      targetRevision: 3.12.0
      helm:
        releaseName: 'metrics-server'
        valueFiles:
          - $values/clusters/k8s-home/argocd/apps/system/metrics-server/values.yaml
