---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-ctrl
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    directory:
      include: '*/application.yaml'
      jsonnet: {}
      recurse: true
    path: k8s/k3s-home/argocd
    repoURL: https://github.com/sebastiaankok/k8s-homelab.git
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-private-ctrl
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    directory:
      include: '*/application.yaml'
      jsonnet: {}
      recurse: true
    path: .
    repoURL: git@github.com:sebastiaankok/gitops-private.git
    targetRevision: HEAD
