# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/library/common/values.schema.json
controllers:
  home-assistant:
    pod:
      annotations:
        backup.velero.io/backup-volumes: config
        backup.velero.io/backup-volumes-excludes: tmpfs
    containers:
      app:
        image:
          repository: ghcr.io/home-operations/home-assistant
          tag: 2025.10.2
        resources:
          requests:
            cpu: 10m
            memory: 250Mi
          limits:
            memory: 1Gi
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - ALL
service:
  app:
    controller: home-assistant
    ports:
      http:
        port: 8123

ingress:
  app:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
      nginx.org/websocket-services: home-assistant
    hosts:
      - host: hass.otohgunga.nl
        paths:
          - path: /
            service:
              identifier: app
              port: http
            pathType: Prefix
    tls:
      - hosts:
          - hass.otohgunga.nl
        secretName: hass-https-tls

persistence:
  config:
    enabled: true
    existingClaim: local-hass-pvc
    globalMounts:
      - path: /config

  tmpfs:
    type: emptyDir
    advancedMounts:
      home-assistant:
        app:
          - path: /tmp
            subPath: hass-tmp
