---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/library/common/values.schema.json
defaultPodOptions:
  imagePullSecrets:
    - name: ghcr-secret
controllers:
  wodplanner:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: ghcr.io/sebastiaankok/wodplanner
          tag: 0.7.0
          pullPolicy: Always
        resources:
          requests:
            cpu: 10m
            memory: 250Mi
          limits:
            memory: 1Gi
        env:
          ENVIRONMENT: "production"
          API_CACHE_TTL_SECONDS: 86400
        envFrom:
          - secretRef:
              name: wodplanner-secret
        securityContext:
          runAsUser: 1010
          runAsGroup: 1010
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
  backup:
    cronjob:
      backoffLimit: 2
      concurrencyPolicy: Forbid
      failedJobsHistory: 1
      schedule: "0 1 * * *"
      startingDeadlineSeconds: 30
      successfulJobsHistory: 0
      suspend: false
    type: cronjob
    strategy: RollingUpdate
    containers:
      app:
        command:
          - backup-db
          - --db-path
          - /data/wodplanner.db
          - --backup-dir
          - /data/backups
          - --keep
          - "7"
        image:
          repository: ghcr.io/sebastiaankok/wodplanner
          tag: 0.7.0
          pullPolicy: Always
        resources:
          requests:
            cpu: 10m
            memory: 250Mi
          limits:
            memory: 1Gi


service:
  app:
    controller: wodplanner
    ports:
      http:
        port: 8000

ingress:
  app:
    enabled: false

persistence:
  config:
    enabled: true
    existingClaim: local-wodplanner-pvc
    globalMounts:
      - path: /data
