# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/library/common/values.schema.json
controllers:
  sabnzbd:
    annotations:
      reloader.stakater.com/auto: "true"

    pod:
      securityContext:
        runAsUser: 992
        runAsGroup: 990
        runAsNonRoot: true
        fsGroup: 990
        fsGroupChangePolicy: OnRootMismatch
    pod:
      annotations:
        backup.velero.io/backup-volumes: config
        backup.velero.io/backup-volumes-excludes: downloads,tmpfs

    containers:
      app:
        image:
          repository: ghcr.io/home-operations/sabnzbd
          tag: 4.5.3
        env:
          SABNZBD__PORT: &port 8080
          SABNZBD__HOST_WHITELIST_ENTRIES: >-
            sabnzbd,
            sabnzbd.media,
            sabnzbd.media.svc,
            sabnzbd.media.svc.cluster,
            sabnzbd.media.svc.cluster.local,
            sabnzbd.otohgunga.nl
        envFrom:
          - secretRef:
              name: sabnzbd-secret
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api?mode=version
                port: *port
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
        resources:
          requests:
            cpu: 5m
            memory: 1Gi
          limits:
            memory: 12Gi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL

service:
  app:
    ports:
      http:
        port: *port

persistence:
  config:
    existingClaim: local-sabnzbd-pvc
    advancedMounts:
      sabnzbd:
        app:
          - path: /config
  downloads:
    existingClaim: local-media-pvc
    globalMounts:
      - path: /data/library
  tmpfs:
    type: emptyDir
    globalMounts:
      - path: /config/logs
        subPath: logs
      - path: /tmp
        subPath: tmp

ingress:
  app:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
    hosts:
      - host: sabnzbd.otohgunga.nl
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - secretName: sabnzbd-https-tls
        hosts:
          - sabnzbd.otohgunga.nl
