controllers:
  main:
    pod:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        runAsNonRoot: true
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/sabnzbd
          tag: 4.4.1@sha256:36674664a94760ae934c09b1d97546a3e79a0f110edda88085e74778c26d68e3
        env:
          SABNZBD__PORT: &port 8080
          SABNZBD__HOST_WHITELIST_ENTRIES: >-
            sabnzbd,
            sabnzbd.plex,
            sabnzbd.plex.svc,
            sabnzbd.plex.svc.cluster,
            sabnzbd.plex.svc.cluster.local,
            sabnzbd.example.com
        resources:
          requests:
            cpu: 5m
            memory: 1024Mi
          limits:
            memory: 6144Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL

service:
  main:
    controller: main
    ports:
      http:
        port: *port

ingress:
  main:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
    hosts:
      - host: "sabnzbd.example.com"
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - "sabnzbd.example.com"
        secretName: "sabnzbd-otohgunga-tls"

persistence:
  config:
    enabled: true
    existingClaim: hostpath-sabnzbd-pvc
    advancedMounts:
      main:
        main:
          - path: /config
  media:
    type: hostPath
    hostPath: /data/library/
    globalMounts:
      - path: /data/nas-media-ssd

  download:
    type: hostPath
    hostPath: /data/library/dl/incomplete
    advancedMounts:
      main:
        main:
          - path: /data/incomplete

  tmp:
    type: emptyDir
    medium: Memory
    advancedMounts:
      main:
        main:
          - path: /tmp
