# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/library/common/values.schema.json
---
defaultPodOptions:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
    seccompProfile:
      type: RuntimeDefault

controllers:
  calibre-web-automated:
    containers:
      app:
        image:
          repository: ghcr.io/crocodilestick/calibre-web-automated
          tag: v4.0.6@sha256:c31a738b6d5ec6982c050063dd3f063b6943eb1051fc81144789f840d9093a8d
        env:
          CACHE_DIR: /cache
          NETWORK_SHARE_MODE: false
          S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES: 1
          S6_READ_ONLY_ROOT: 1
        securityContext:
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - ALL
            add:
              - CHOWN
              - SETUID
              - SETGID
              - FOWNER
              - DAC_OVERRIDE
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                port: &port 8083
                path: /login
          readiness: *probes
        resources:
          requests:
            cpu: 50m
            memory: 200Mi
          limits:
            memory: 600Mi

service:
  app:
    controller: calibre-web-automated
    ports:
      http:
        port: *port

route:
  app:
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Calibre Web Automated"
      gethomepage.dev/icon: "calibre-web"
      gethomepage.dev/group: "Media"
      gethomepage.dev/description: Ebook library management
    parentRefs:
      - name: internal
        namespace: kube-system
        sectionName: https
    hostnames:
      - "calibre.otohgunga.nl"
    rules:
      - backendRefs:
          - identifier: app
            port: *port

persistence:
  config:
    existingClaim: calibre-config-v1
    globalMounts:
      - path: /config
  library:
    existingClaim: calibre-config-v1
    globalMounts:
      - path: /calibre-library
        subPath: library
  ingest:
    existingClaim: calibre-config-v1
    globalMounts:
      - path: /cwa-book-ingest
        subPath: ingest
  tmpfs:
    type: emptyDir
    globalMounts:
      - path: /cache
        subPath: cache
      - path: /tmp
        subPath: tmp
      - path: /run
        subPath: run
