apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-nextcloud-pv
  namespace: nextcloud
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: hostpath-nextcloud
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/nextcloud/nextcloud"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-nextcloud-pvc
  namespace: nextcloud
spec:
  storageClassName: hostpath-nextcloud
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
