---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgresql-18
  namespace: immich
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
    # This extension is loaded via the Database CRD at cloudnative-pg-database.yaml
    extensions:
      - name: vchord
        image:
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.1.1
        dynamic_library_path:
          - /usr/lib/postgresql/18/lib
        extension_control_path:
          - /usr/share/postgresql/18/
    # parameters:
    #   shared_buffers: 256MB
    #   pg_stat_statements.max: '10000'
    #   pg_stat_statements.track: all
    #   auto_explain.log_min_duration: '10s'
    # pg_hba:
    #   - host all all 10.42.0.0/16 md5

  storage:
    storageClass: local-immich-postgresql-18
    size: 1Gi

  # plugins:
  #   - name: barman-cloud.cloudnative-pg.io
  #     isWALArchiver: true
  #     parameters:
  #       barmanObjectName: backblazeb2
  #       serverName: immich-postgresql-18
  #
  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "2"

  # affinity:
  #   enablePodAntiAffinity: false
  #
  # nodeMaintenanceWindow:
  #   inProgress: false
  #   reusePVC: false
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich-database-18
spec:
  name: app
  owner: app
  cluster:
    name: immich-postgresql-18
  extensions:
    - name: vector
      ensure: present
    - name: vchord
      ensure: present
    - name: earthdistance
      ensure: present
    - name: cube
      ensure: present
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-postgresql-18-backup-schedule
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  cluster:
    name: immich-postgresql-18
