apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: cnpg-system
  sources:
    - repoURL: 'https://github.com/sebastiaankok/k8s-homelab.git'
      targetRevision: main
      ref: values
      path: "clusters/k8s-home/argocd/apps/databases/cnpg-operator/"
      directory:
        exclude: '{application.yaml,values.yaml}'
    - chart: cloudnative-pg
      repoURL: 'https://cloudnative-pg.io/charts/'
      targetRevision: 0.26.0
      helm:
        releaseName: "cnpg-operator"
        valueFiles:
          - $values/clusters/k8s-home/argocd/apps/databases/cnpg-operator/values.yaml
