apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: nextcloud
  sources:
    - repoURL: 'git@github.com:sebastiaankok/k8s-homelab.git'
      targetRevision: main
      path: "clusters/k8s-home/argocd/apps/nextcloud/"
      directory:
        exclude: '{application.yaml,values.yaml}'
    - chart: nextcloud
      repoURL: 'https://nextcloud.github.io/helm/'
      targetRevision: 4.6.2
      helm:
        releaseName: "nextcloud"
        valueFiles:
          - $values/clusters/k8s-home/argocd/apps/nextcloud/values.yaml
    - repoURL: 'git@github.com:sebastiaankok/k8s-homelab.git'
      targetRevision: main
      ref: values
