---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-scale-set-wodplanner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: arc-runners
  sources:
    - repoURL: 'https://github.com/sebastiaankok/k8s-homelab.git'
      targetRevision: main
      ref: values
      path: "k8s/k3s-home/argocd/system/gha-runner-scale-set-wodplanner/"
      directory:
        exclude: '{application.yaml,values.yaml}'
    - repoURL: 'ghcr.io/actions/actions-runner-controller-charts'
      chart: 'gha-runner-scale-set-wodplanner'
      targetRevision: 0.14.1
      helm:
        releaseName: "gha-runner-scale-set"
        valueFiles:
          - $values/k8s/k3s-home/argocd/system/gha-runner-scale-set-wodplanner/values.yaml
