---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgresql-15
  namespace: immich
spec:
  description: ""
  # psvector image to do migration
  # imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:15.13
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:15-0.3.0
  instances: 1
  primaryUpdateStrategy: unsupervised

  postgresql:
    shared_preload_libraries:
      # psvectors library to do migration
      #- "vectors.so"
      - "vchord.so"

    parameters:
      shared_buffers: 256MB
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: all
      auto_explain.log_min_duration: '10s'
    pg_hba:
      - host all all 10.42.0.0/16 md5

  managed:
    roles:
    - name: immich
      connectionLimit: -1
      inherit: true
      ensure: present
      comment: Immich
      login: true
      superuser: true
      passwordSecret:
        name: postgresql-user-immich

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: postgresql-user-immich
      postInitSQL:
       - CREATE EXTENSION IF NOT EXISTS "vector";
       - CREATE EXTENSION IF NOT EXISTS "vchord" CASCADE;
       - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
       - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;

  enableSuperuserAccess: true
  superuserSecret:
    name: immich-postgresql-15-superuser

  storage:
    storageClass: local-immich-postgresql-15
    size: 1Gi

  backup:
    barmanObjectStore:
      destinationPath: s3://cnpg-operator/immich/postgresql-15
      endpointURL: https://s3.eu-central-003.backblazeb2.com
      s3Credentials:
        accessKeyId:
          name: cnpg-b2-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-b2-credentials
          key: ACCESS_SECRET_KEY
        region:
          name: cnpg-b2-credentials
          key: ACCESS_REGION
      wal:
        compression: gzip
        encryption: AES256
      data:
        compression: gzip
        encryption: AES256
        immediateCheckpoint: false
        jobs: 2
    retentionPolicy: "14d"

  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "2"

  affinity:
    enablePodAntiAffinity: false

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: false
