controllers:
  server:
    strategy: RollingUpdate
    annotations:
      reloader.stakater.com/auto: "true"
    pod:
      enableServiceLinks: false
      securityContext:
        runAsUser: 1006
        runAsGroup: 1006
        runAsNonRoot: true
      annotations:
        backup.velero.io/backup-volumes: library
        backup.velero.io/backup-volumes-excludes: cache, matplotlib, tmpfs
    containers:
      main:
        image:
          repository: ghcr.io/immich-app/immich-server
          tag: v1.141.1
        env:
          IMMICH_MEDIA_LOCATION: &mediaLocation /data/immich
          DB_USERNAME:
            valueFrom:
              secretKeyRef:
                name: postgresql-user-immich
                key: username
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: postgresql-user-immich
                key: password
        envFrom:
          - configMapRef:
              name: immich-configmap
          - secretRef:
              name: immich-secret

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 4096Mi

  machine-learning:
    strategy: RollingUpdate
    annotations:
      reloader.stakater.com/auto: "true"
    pod:
      enableServiceLinks: false
      securityContext:
        runAsUser: 1006
        runAsGroup: 1006
        runAsNonRoot: true
      annotations:
        backup.velero.io/backup-volumes-excludes: library, cache, matplotlib, tmpfs
    containers:
      main:
        image:
          repository: ghcr.io/immich-app/immich-machine-learning
          tag: v1.142.0
        envFrom:
          - secretRef:
              name: immich-secret
          - configMapRef:
              name: immich-configmap
        env:
          MPLCONFIGDIR: "/cache/matplotlib"
          IMMICH_MEDIA_LOCATION: *mediaLocation
        resources:
          requests:
            cpu: 100m
            memory: 274M
          limits:
            memory: 3949M

  valkey:
    containers:
      app:
        image:
          repository: valkey/valkey
          tag: 8.1.3

service:
  server:
    controller: server
    ports:
      http:
        port: &port 2283
  machine-learning:
    controller: machine-learning
    ports:
      http:
        port: 3003
  valkey:
    controller: valkey
    ports:
      http:
        port: 6379

ingress:
  main:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
    hosts:
      - host: immich.otohgunga.nl
        paths:
          - path: /
            service:
              identifier: server
              port: http
    tls:
      - secretName: immich-https-tls
        hosts:
          - immich.otohgunga.nl

persistence:
  matplotlib:
    type: emptyDir
    advancedMounts:
      server:
        main:
          - path: /config/matplotlib

  library:
    type: persistentVolumeClaim
    existingClaim: local-immich-data-pvc
    globalMounts:
      - path: *mediaLocation

  cache:
    type: persistentVolumeClaim
    existingClaim: local-immich-ml-cache-pvc
    globalMounts:
      - path: /cache
        subPath: cache
      - path: /.cache
        subPath: dotCache

  tmpfs:
    type: emptyDir
    advancedMounts:
      server:
        main:
          - path: /usr/src/app/.reverse-geocoding-dump
            subPath: geocoding
          - path: /usr/src/app/.transformers_cache
            subPath: transformers
