apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgresql-17
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local-postgresql-17
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/data/databases/postgresql-17"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-home
