apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-media-pv
  labels:
    app.kubernetes.io/name: media
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local-media
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/storage/library"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-home
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-media-pvc
  namespace: media
  labels:
    app.kubernetes.io/name: media
spec:
  storageClassName: local-media
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
