# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/library/common/values.schema.json
controllers:
  jellyfin:
    annotations:
      reloader.stakater.com/auto: "true"
    pod:
      securityContext:
        runAsUser: 992
        runAsGroup: 990
        runAsNonRoot: true
        fsGroup: 990
        fsGroupChangePolicy: "OnRootMismatch"
      annotations:
        backup.velero.io/backup-volumes: config
        backup.velero.io/backup-volumes-excludes: media,tmpfs
    containers:
      app:
        image:
          repository: ghcr.io/jellyfin/jellyfin
          tag: 10.10.7@sha256:e4d1dc5374344446a3a78e43dd211247f22afba84ea2e5a13cbe1a94e1ff2141
        env:
          TZ: Europe/Amsterdam
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /health
                port: &port 8096
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities: {drop: ["ALL"]}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 8Gi
service:
  app:
    ports:
      http:
        port: *port

persistence:
  config:
    existingClaim: local-jellyfin-pvc
    globalMounts:
      - path: /config
  media:
    existingClaim: local-media-pvc
    globalMounts:
      - path: /data/library
  tmpfs:
    type: emptyDir
    advancedMounts:
      jellyfin:
        app:
          - path: /cache
            subPath: cache
          - path: /config/log
            subPath: log
          - path: /tmp
            subPath: tmp

ingress:
  app:
    enabled: true
    className: ingress-nginx-media
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
    hosts:
      - host: jellyfin.otohgunga.nl
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - secretName: jellyfin-https-tls
        hosts:
          - jellyfin.otohgunga.nl
