# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/library/common/values.schema.json
---
controllers:
  homepage:
    pod:
      automountServiceAccountToken: true
    strategy: Recreate
    annotations:
      reloader.stakater.com/search: "true"

    containers:
      app:
        image:
          repository: ghcr.io/gethomepage/homepage
          tag: v2.2.0@sha256:753eeb0cc22ab7baad39ed47cbd1aae14e193dd1b264e965f193a9ea1d1e1bdd
        env:
          TZ: Europe/Amsterdam
          LOG_LEVEL: debug
          HOMEPAGE_ALLOWED_HOSTS: "homepage.otohgunga.nl"
        envFrom:
          - secretRef:
              name: homepage-secret
        resources:
          requests:
            cpu: 25m
            memory: 105M
          limits:
            memory: 225M
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
    serviceAccount:
      identifier: homepage

# serviceAccount:
#   homepage:

service:
  app:
    controller: homepage
    ports:
      http:
        port: 3000

route:
  app:
    annotations: {}
    parentRefs:
      - name: internal
        namespace: kube-system
        sectionName: https
    hostnames:
      - "homepage.otohgunga.nl"
    rules:
      - backendRefs:
          - identifier: app
            port: 3000

persistence:
  storage:
    existingClaim: local-homepage-pvc
    globalMounts:
      - path: /storage
  config:
    type: configMap
    name: homepage-config
    globalMounts:
      - subPath: kubernetes.yaml
        path: /app/config/kubernetes.yaml
      - subPath: docker.yaml
        path: /app/config/docker.yaml
      - subPath: settings.yaml
        path: /app/config/settings.yaml
      - subPath: bookmarks.yaml
        path: /app/config/bookmarks.yaml
      - subPath: services.yaml
        path: /app/config/services.yaml
      - subPath: widgets.yaml
        path: /app/config/widgets.yaml
