apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-frigate-pv
  namespace: frigate
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local-frigate
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data/frigate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-home

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-frigate-pvc
  namespace: frigate
spec:
  storageClassName: local-frigate
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

