apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-frigate-config-pv
  namespace: nvr
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: hostpath-frigate-config
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/nvr/frigate-config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-frigate-config-pvc
  namespace: nvr
spec:
  storageClassName: hostpath-frigate-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
