controllers:
  frigate:
    containers:
      app:
        image:
          repository: ghcr.io/blakeblackshear/frigate
          tag: 0.15.2
        env:
          FRIGATE_RTSP_ARENTI_USER:
            valueFrom:
              secretKeyRef:
                name: camera-rtsp-config
                key: FRIGATE_RTSP_ARENTI_USER
          FRIGATE_RTSP_ARENTI_PASS:
            valueFrom:
              secretKeyRef:
                name: camera-rtsp-config
                key: FRIGATE_RTSP_ARENTI_PASS
          FRIGATE_RTSP_ARENTI2_USER:
            valueFrom:
              secretKeyRef:
                name: camera-rtsp-config
                key: FRIGATE_RTSP_ARENTI2_USER
          FRIGATE_RTSP_ARENTI2_PASS:
            valueFrom:
              secretKeyRef:
                name: camera-rtsp-config
                key: FRIGATE_RTSP_ARENTI2_PASS
          FRIGATE_RTSP_DOORBELL_USER:
            valueFrom:
              secretKeyRef:
                name: camera-rtsp-config
                key: FRIGATE_RTSP_DOORBELL_USER
          FRIGATE_RTSP_DOORBELL_PASS:
            valueFrom:
              secretKeyRef:
                name: camera-rtsp-config
                key: FRIGATE_RTSP_DOORBELL_PASS
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/version
                port: &port 5000
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: false
        resources:
          requests:
            cpu: 500m
            memory: 1.5Gi
          limits:
            memory: 5Gi
        securityContext:
          runAsUser: 1002
          runAsGroup: 1002
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - ALL

service:
  app:
    controller: frigate
    ports:
      http:
        port: *port

ingress:
  app:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
    hosts:
      - host: frigate.otohgunga.nl
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - secretName: frigate-https-tls
        hosts:
          - frigate.otohgunga.nl

persistence:
  data:
    enabled: true
    #existingClaim: hostpath-frigate-data-pvc
    existingClaim: hostpath-frigate-pvc
    globalMounts:
      - path: /data
  config:
    enabled: true
    #existingClaim: hostpath-frigate-config-pvc
    existingClaim: hostpath-frigate-pvc
    globalMounts:
      - path: /config
  media:
    enabled: true
    #existingClaim: hostpath-frigate-media-pvc
    existingClaim: hostpath-frigate-pvc
    globalMounts:
      - path: /media
  cache:
    enabled: true
    type: emptyDir
    medium: Memory
    sizeLimit: 128Mi
    globalMounts:
      - path: /dev/shm
  # renderD128:
  #   enabled: true
  #   type: hostPath
  #   hostPath: /dev/dri/renderD128
  #   globalMounts:
  #     - path: /dev/dri/renderD128
