# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/library/common/values.schema.json
controllers:
  prowlarr:
    annotations:
      reloader.stakater.com/auto: "true"

    pod:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      annotations:
        backup.velero.io/backup-volumes: config

    containers:
      app:
        image:
          repository: ghcr.io/home-operations/prowlarr
          tag: 2.1.4.5212
        env:
          PROWLARR__APP__INSTANCENAME: Prowlarr
          PROWLARR__AUTH__METHOD: External
          PROWLARR__LOG__DBENABLED: "False"
          PROWLARR__LOG__LEVEL: info
          PROWLARR__SERVER__PORT: &port 9696
          PROWLARR__UPDATE__BRANCH: develop
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: *port
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
        resources:
          requests:
            cpu: 18m
            memory: 128Mi
          limits:
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL

service:
  app:
    ports:
      http:
        port: *port

ingress:
  app:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
    hosts:
      - host: prowlarr.otohgunga.nl
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - secretName: prowlarr-https-tls
        hosts:
          - prowlarr.otohgunga.nl

persistence:
  config:
    existingClaim: local-prowlarr-pvc
