apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-hass-pv
  namespace: home-automation
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local-hass
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/data/home-assistant"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-home
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-hass-pvc
  namespace: home-automation
spec:
  storageClassName: local-hass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
