apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-hass-pv
  namespace: hass
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: hostpath-hass
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/hass/hass"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-hass-pvc
  namespace: hass
spec:
  storageClassName: hostpath-hass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
