controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/home-assistant/home-assistant
          tag: 2025.9.1
        env:
          TZ: UTC
        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
          startup:
            enabled: false
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 1Gi

service:
  main:
    controller: main
    ports:
      http:
        port: 8123

ingress:
  main:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
      nginx.org/websocket-services: home-assistant
    hosts:
      - host: hass.example.com
        paths:
          - path: /
            service:
              identifier: main
              port: http
            pathType: Prefix
    tls:
      - hosts:
          - hass.example.com
        secretName: hass-otohgunga-tls

persistence:
  config:
    enabled: true
    existingClaim: hostpath-hass-pvc
    globalMounts:
      - path: /config
