controllers:
  home-assistant:
    containers:
      app:
        image:
          repository: ghcr.io/home-assistant/home-assistant
          tag: 2025.8.0
        resources:
          requests:
            cpu: 10m
            memory: 250Mi
          limits:
            memory: 1Gi
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
service:
  app:
    controller: home-assistant
    ports:
      http:
        port: 8123

ingress:
  app:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
      nginx.org/websocket-services: home-assistant
    hosts:
      - host: hass.otohogunga.nl
        paths:
          - path: /
            service:
              identifier: app
              port: http
            pathType: Prefix
    tls:
      - hosts:
          - hass.otohogunga.nl
        secretName: hass-https-tls

persistence:
  config:
    enabled: true
    existingClaim: hostpath-hass-pvc
    globalMounts:
      - path: /config
