apiVersion: v1
kind: ConfigMap
metadata:
  name: kamstrup-config
  namespace: home-automation
data:
  config.yaml: |
    mqtt:
        host: mosquitto.otohgunga.nl
        port: 1883
        client: kamstrup
        topic: kamstrup
        qos: 0
        retain: False
        authentication: False
        username: user1
        password: changeit
    serial_device:
        com_port: /dev/pts/0
    kamstrup:
        parameters:
        - energy
        - volume
        - temp1
        - temp2
        - tempdiff
        poll_interval: 1
