controllers:
  kamstrup-mqtt:
    containers:
      app:
        image:
          repository: ghcr.io/sebastiaankok/kamstrup-402-mqtt
          tag: 900ec8a4dddd97e6216989765f74a601c71a8b7b
        securityContext:
          runAsUser: 1003
          runAsGroup: 1003
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            memory: 512Mi
        command:
          - /bin/bash
          - -c
        args:
          - |
            echo "Waiting for socket..."
            until [ -S /dev/pts/0 ]; do
              sleep 2
            done
            echo "Socket found, starting app"
            python /opt/kamstrup/daemon.py
      socat:
        image:
          repository: alpine/socat
          tag: 1.8.0.3
        command:
          - socat
        args:
         - "pty,raw,echo=0,link=/dev/ser2net/kamstrup-serial,mode=0660,owner=1003"
         - "tcp:rpi4-ser2net.otohgunga.nl:20408"

        securityContext:
          runAsUser: 1003
          runAsGroup: 1003
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL


service:
  app:
    enabled: false

ingress:
  app:
    enabled: false

persistence:
  config:
    enabled: true
    type: configMap
    name: kamstrup-config
    advancedMounts:
      kamstrup-mqtt:
        app:
          - path: /opt/kamstrup/config.yaml
            subPath: config.yaml
  serial-socket:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /dev/ser2net
