controllers:
  kamstrup-mqtt:
    containers:
      app:
        image:
          repository: ghcr.io/sebastiaankok/kamstrup-402-mqtt
          tag: 900ec8a4dddd97e6216989765f74a601c71a8b7b
        securityContext:
          runAsUser: 1003
          runAsGroup: 1003
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            memory: 512Mi

service:
  app:
    enabled: false

ingress:
  app:
    enabled: false

persistence:
  config:
    enabled: true
    type: configMap
    name: kamstrup-config
    advancedMounts:
      kamstrup-mqtt:
        app:
          - path: /opt/kamstrup/config.yaml
            subPath: config.yaml
  serial-socket:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /opt/kamstrup/serial

  # -- Temporarily hack until code fixed
  hack:
    enabled: true
    type: configMap
    name: kamstrup-hack
    advancedMounts:
      kamstrup-mqtt:
        app:
          - path: /opt/kamstrup/kamstrup_meter.py
            subPath: kamstrup_meter.py
