apiVersion: v1
data:
  backup.sh: |
    #!/bin/sh

    _rclone() {
        rclone copy "$1" "$2" $3 --progress --copy-links --checkers='10' --transfers='50' --s3-chunk-size='20M' --config /config/rclone.conf
    }

    ## -- Home assistant
    _rclone /data/hass/hass secret:/encrypted/hass/hass

    _rclone /data/hass/zigbee2mqtt secret:/encrypted/hass/zigbee2mqtt
    _rclone /data/hass/mosquitto secret:/encrypted/hass/mosquitto

    ## -- Plex
    _rclone "/data/plex/plex/Library/Application Support/Plex Media Server/Preferences.xml" secret:/encrypted/plex/plex
    _rclone /data/plex/overseerr/ secret:/encrypted/plex/overseerr
    _rclone /data/plex/prowlarr/Backups secret:/encrypted/plex/prowlarr
    _rclone /data/plex/radarr/Backups secret:/encrypted/plex/radarr
    _rclone /data/plex/sonarr/Backups secret:/encrypted/plex/sonarr
    _rclone /data/plex/sabnzbd/sabnzbd.ini secret:/encrypted/plex/sabnzbd
kind: ConfigMap
metadata:
  name: rclone-script
  namespace: kube-system
