namespaceOverride: monitoring
hostNetwork: true
hostPID: true
hostRootFsMount:
  enabled: true
  mountPropagation: HostToContainer
priorityClassName: system-node-critical
extraArgs:
  - --no-collector.softnet
  - --no-collector.schedstat
  - --collector.netclass.ignored-devices=^(cilium_|lxc|cali|veth|dummy|tunl|kube|vxlan|cbr|docker|flannel|geneve)
  - --collector.filesystem.mount-points-include=^(/|/storage)$
service:
  port: 9100
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    memory: 256Mi