apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: plex
  sources:
    - repoURL: 'git@github.com:sebastiaankok/k8s-homelab.git'
      targetRevision: main
      path: "clusters/k8s-home/argocd/apps/downloads/radarr/"
      directory:
        exclude: '{application.yaml,values.yaml}'
    - chart: app-template
      repoURL: 'https://bjw-s.github.io/helm-charts'
      targetRevision: 3.7.3
      helm:
        releaseName: "radarr"
        valueFiles:
          - $values/clusters/k8s-home/argocd/apps/downloads/radarr/values.yaml
    - repoURL: 'git@github.com:sebastiaankok/k8s-homelab.git'
      targetRevision: main
      ref: values
