apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-radarr-pv
  namespace: downloads
  labels:
    app.kubernetes.io/name: radarr
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local-radarr
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/data/mediaserver/radarr"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-home
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-radarr-pvc
  namespace: downloads
  labels:
    app.kubernetes.io/name: radarr
spec:
  storageClassName: local-radarr
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
