controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/radarr
          tag: 5.9.1.9070@sha256:f43d8769d48a201061b7e3d45887b4d80e0baa9a85f3f0f9ae60d0240ba39875
        env:
          RADARR__INSTANCE_NAME: Radarr
          RADARR__PORT: &port 7878
          RADARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
          RADARR__APPLICATION_URL: "https://radarr.otohgunga.nl"
          RADARR__LOG_LEVEL: info
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - ALL
persistence:
  config:
    enabled: true
    existingClaim: hostpath-radarr-pvc
    advancedMounts:
      main:
        main:
          - path: /config
  media:
    enabled: true
    type: hostPath
    hostPath: /data/library
    advancedMounts:
      main:
        main:
          - path: /data/nas-media-ssd

service:
  main:
    ports:
      http:
        port: *port

ingress:
  main:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
    hosts:
      - host: "radarr.otohgunga.nl"
        paths:
          - path: /
            service:
              name: main
              port: http
    tls:
      - hosts:
          - "radarr.otohgunga.nl"
        secretName: "radarr-otohgunga-tls"
