apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: nextcloud-backup-schedule
  namespace: pg-nextcloud
spec:
  schedule: "0 0 5 1/1 * *" # every day at 4 am, see https://crontab.cronhub.io/
  backupOwnerReference: self
  immediate: true
  cluster:
    name: pg-nextcloud
  target: primary
