#apiVersion: postgresql.cnpg.io/v1
#kind: Cluster
#metadata:
#  name: pg-nextcloud-restored
#  namespace: pg-nextcloud
#spec:
#  instances: 1
#  imageName: ghcr.io/cloudnative-pg/postgresql:15 # which PG version to use
#  bootstrap:
#    recovery:
#      source: clusterBackup
#  storage:
#    pvcTemplate:
#      accessModes:
#        - ReadWriteOnce
#      resources:
#        requests:
#          storage: 10Gi
#      storageClassName: local-path
#  externalClusters:
#    - name: clusterBackup
#      barmanObjectStore:
#        serverName: "pg-nextcloud"
#        endpointURL: "https://s3.eu-central-003.backblazeb2.com/"
#        destinationPath: "s3://k3s-homelab/pg-backups"
#        s3Credentials:
#          accessKeyId:
#            name: s3-creds
#            key: ACCESS_KEY_ID
#          secretAccessKey:
#            name: s3-creds
#            key: ACCESS_SECRET_KEY
