apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-plex-pv
  namespace: plex
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: hostpath-plex
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/plex/plex"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-plex-pvc
  namespace: plex
spec:
  storageClassName: hostpath-plex
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
