controllers:
  main:
    pod:
      securityContext:
        runAsUser: 568
        runAsGroup: 568

    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/plex
          tag: 1.41.0.8994-f2c27da23@sha256:8e1a094b0cd9c980e2b2e22daf2c2b212893bdb8e1e9e6452aefba9448466ff1
        resources:
          requests:
            cpu: 100m
            memory: 9248M
          limits:
            memory: 9248M

service:
  main:
    controller: main
    type: LoadBalancer
    externalTrafficPolicy: Cluster
    loadBalancerIP: 10.10.21.85
    annotations:
      io.cilium/lb-ipam-ips: "10.10.21.85"
    ports:
      http:
        port: 32400

ingress:
  main:
    enabled: true
    className: ingress-nginx-plex
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      cert-manager.io/cluster-issuer: letsencrypt-dns
    hosts:
      - host: "plex.otohgunga.nl"
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - "plex.otohgunga.nl"
        secretName: "plex-otohgunga-tls"

persistence:
  config:
    enabled: true
    existingClaim: hostpath-plex-pvc
    advancedMounts:
      main:
        main:
          - path: /config
  nfs-nas-media:
    type: hostPath
    hostPath: /data/library
    advancedMounts:
      main:
        main:
          - path: /data/nas-media-ssd/
  transcode:
    type: emptyDir
    medium: Memory
    advancedMounts:
      main:
        main:
          - path: /transcode
