controllers:
  main:
    pod:
      securityContext:
        runAsUser: 568 
        runAsGroup: 568 

    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/plex
          tag: 1.40.1.8227-c0dd5a73e@sha256:4ca8db0ffa1bee5a2976a0385cc43368112e81a2485b80d0fff3b04c9d5bd1ca
        resources:
          requests:
            cpu: 100m
            memory: 9248M
          limits:
            memory: 9248M

service:
  main:
    type: LoadBalancer
    externalTrafficPolicy: Cluster
    loadBalancerIP: 10.10.21.85
    annotations:
      io.cilium/lb-ipam-ips: "10.10.21.85"
    ports:
      http:
        port: 32400

ingress:
  main:
    enabled: true
    className: ingress-nginx-plex
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      cert-manager.io/cluster-issuer: letsencrypt-dns
    hosts:
      - host: "plex.example.com"
        paths:
          - path: /
            service:
              name: main
              port: http
    tls:
      - hosts:
          - "plex.example.com"
        secretName: "plex-otohgunga-tls"

persistence:
  config:
    enabled: true
    existingClaim: hostpath-plex-pvc 
    advancedMounts:
      main:
        main:
          - path: /config
  nfs-nas-media:
    type: hostPath
    hostPath: /data/library 
    advancedMounts:
      main:
        main:
          - path: /data/nas-media-ssd/
  transcode:
    type: emptyDir
    medium: Memory
    advancedMounts:
      main:
        main:
          - path: /transcode
