# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/library/common/values.schema.json
controllers:
  main:
    pod:
      securityContext:
        runAsUser: 568
        runAsGroup: 568

    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/plex
          tag: 1.41.5.9522@sha256:6d393c4eee152100bd6762a94bdd891b8c80c1c8a914a7f906b4097ab69fd557
        resources:
          requests:
            cpu: 100m
            memory: 9248M
          limits:
            memory: 9248M

service:
  main:
    controller: main
    type: LoadBalancer
    externalTrafficPolicy: Cluster
    loadBalancerIP: 10.10.21.85
    annotations:
      io.cilium/lb-ipam-ips: "10.10.21.85"
    ports:
      http:
        port: 32400

ingress:
  main:
    enabled: true
    className: ingress-nginx-plex
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      cert-manager.io/cluster-issuer: letsencrypt-dns
    hosts:
      - host: "plex.example.com"
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - "plex.example.com"
        secretName: "plex-https-tls"

persistence:
  config:
    enabled: true
    existingClaim: hostpath-plex-pvc
    advancedMounts:
      main:
        main:
          - path: /config
  nfs-nas-media:
    type: hostPath
    hostPath: /data/library
    advancedMounts:
      main:
        main:
          - path: /data/nas-media-ssd/
  transcode:
    type: emptyDir
    medium: Memory
    advancedMounts:
      main:
        main:
          - path: /transcode
