controller:
  kind: Deployment
  priorityClassName: system-cluster-critical
  watchIngressWithoutClass: true
  service:
    externalTrafficPolicy: Local
    loadBalancerIP: 10.10.21.30
  config:
    disable-access-log: "false"
