# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/library/common/values.schema.json
controllers:
  sonarr:
    annotations:
      reloader.stakater.com/auto: "true"

    pod:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      annotations:
        backup.velero.io/backup-volumes: config
        backup.velero.io/backup-volumes-excludes: media,tmpfs

    containers:
      app:
        image:
          repository: ghcr.io/home-operations/sonarr
          tag: 4.0.16.2942
        env:
          SONARR__APP__INSTANCENAME: Sonarr
          SONARR__AUTH__METHOD: External
          SONARR__AUTH__REQUIRED: DisabledForLocalAddresses
          SONARR__LOG__DBENABLED: "False"
          SONARR__LOG__LEVEL: info
          SONARR__SERVER__PORT: &port 8989
          SONARR__UPDATE__BRANCH: develop
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: *port
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
        resources:
          requests:
            cpu: 20m
            memory: 384Mi
          limits:
            memory: 2Gi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL

service:
  app:
    ports:
      http:
        port: *port

persistence:
  config:
    existingClaim: local-sonarr-pvc
  tmpfs:
    type: emptyDir
    globalMounts:
      - path: /tmp
        subPath: tmp
  media:
    existingClaim: local-media-pvc
    globalMounts:
      - path: /data/library

ingress:
  app:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
    hosts:
      - host: sonarr.otohgunga.nl
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - secretName: sonarr-https-tls
        hosts:
          - sonarr.otohgunga.nl
