apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-mosquitto-pv
  namespace: hass
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: hostpath-mosquitto
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/hass/mosquitto"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-mosquitto-pvc
  namespace: hass
spec:
  storageClassName: hostpath-mosquitto
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
