# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/library/common/values.schema.json
controllers:
  mosquitto:
    containers:
      app:
        image:
          repository: public.ecr.aws/docker/library/eclipse-mosquitto
          tag: 2.0.22
        resources:
          requests:
            cpu: 5m
            memory: 10M
          limits:
            memory: 250M
        securityContext:
          runAsUser: 1005
          runAsGroup: 1005
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL

service:
  app:
    type: LoadBalancer
    loadBalancerIP: 10.10.21.35
    externalTrafficPolicy: Local
    ports:
      http:
        enabled: false
        port: 8080
      mqtt:
        enabled: true
        port: 1883

ingress:
  app:
    enabled: false

persistence:
  data:
    existingClaim: hostpath-mosquitto-pvc
    advancedMounts:
      mosquitto:
        app:
          - path: /mosquitto/data
  mosquitto-configfile:
    type: configMap
    name: mosquitto-config
    advancedMounts:
      mosquitto:
        app:
          - path: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
