apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-sonarr-pv
  namespace: plex
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: hostpath-sonarr
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/plex/sonarr"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-sonarr-pvc
  namespace: plex
spec:
  storageClassName: hostpath-sonarr
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
