controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/sonarr-develop
          tag: 4.0.11.2784@sha256:46b113a978365d68f6d36f5d50a1deca9e636f67fa6ebec5c3175fde0efde34d
        env:
          SONARR__INSTANCE_NAME: Sonarr
          SONARR__PORT: &port 8989
          SONARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
          SONARR__APPLICATION_URL: "https://sonarr.example.com"
          SONARR__LOG_LEVEL: info
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - ALL

persistence:
  config:
    enabled: true
    existingClaim: hostpath-sonarr-pvc
    advancedMounts:
      main:
        main:
          - path: /config
  media:
    enabled: true
    type: hostPath
    hostPath: /data/library
    advancedMounts:
      main:
        main:
          - path: /data/nas-media-ssd

service:
  main:
    controller: main
    ports:
      http:
        port: *port

ingress:
  main:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
    hosts:
      - host: "sonarr.example.com"
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - "sonarr.example.com"
        secretName: "sonarr-otohgunga-tls"
