# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/library/common/values.schema.json
controllers:
  radarr:
    annotations:
      reloader.stakater.com/auto: "true"

    pod:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      annotations:
        backup.velero.io/backup-volumes: config
        backup.velero.io/backup-volumes-excludes: media,tmpfs

    containers:
      app:
        image:
          repository: ghcr.io/home-operations/radarr
          tag: 6.0.3.10276
        env:
          RADARR__APP__INSTANCENAME: Radarr
          RADARR__AUTH__METHOD: External
          RADARR__AUTH__REQUIRED: DisabledForLocalAddresses
          RADARR__LOG__DBENABLED: "False"
          RADARR__LOG__LEVEL: info
          RADARR__SERVER__PORT: &port 7878
          RADARR__UPDATE__BRANCH: develop
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: *port
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
        resources:
          requests:
            cpu: 20m
            memory: 384Mi
          limits:
            memory: 2Gi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL

service:
  app:
    ports:
      http:
        port: *port

persistence:
  config:
    existingClaim: local-radarr-pvc
  tmpfs:
    type: emptyDir
    globalMounts:
      - path: /tmp
        subPath: tmp
  media:
    existingClaim: local-media-pvc
    globalMounts:
      - path: /data/library


ingress:
  app:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
    hosts:
      - host: radarr.otohgunga.nl
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - secretName: radarr-https-tls
        hosts:
          - radarr.otohgunga.nl
