# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/library/common/values.schema.json
---
controllers:
  unifi-controller:
    replicas: 1
    containers:
      app:
        image:
          repository: ghcr.io/Bj0/uniFi-controller
          tag: latest
        env:
          TZ: Europe/Amsterdam
          PGID: "1000"
          PUID: "1000"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            memory: 1Gi
    pod:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
service:
  app:
    controller: unifi-controller
    ports:
      http:
        port: 8080
      https:
        port: 8443
      captportal:
        port: 8880
      gui:
        port: 8843
      stun:
        port: 3478
ingress:
  app:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
      gethomepage.dev/enabled: "true"
    hosts:
      - host: unifi.otohgunga.nl
        paths:
          - path: /
            service:
              identifier: app
              port: http
            pathType: Prefix
    tls:
      - secretName: unifi-https-tls
        hosts:
          - unifi.otohgunga.nl
