apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: argocd
  sources:
    - repoURL: 'git@github.com:sebastiaankok/k8s-homelab.git'
      targetRevision: main
      ref: values
    - repoURL: 'git@github.com:sebastiaankok/k8s-homelab.git'
      targetRevision: main
      path: "clusters/k8s-home/argocd/apps/system/argocd/"
      directory:
        exclude: '{application.yaml,values.yaml}'
    - chart: argo-cd
      repoURL: 'https://argoproj.github.io/argo-helm'
      targetRevision: 7.6.5
      helm:
        releaseName: "argocd"
        valueFiles:
          - $values/clusters/k8s-home/argocd/apps/system/argocd/values.yaml
