# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/library/common/values.schema.json
controllers:
  bazarr:
    annotations:
      reloader.stakater.com/auto: "true"

    pod:
      securityContext:
        runAsUser: 992
        runAsGroup: 990
        runAsNonRoot: true
        fsGroup: 990
        fsGroupChangePolicy: "OnRootMismatch"
      annotations:
        backup.velero.io/backup-volumes: config
        backup.velero.io/backup-volumes-excludes: media,tmpfs

    containers:
      app:
        image:
          repository: ghcr.io/home-operations/bazarr
          tag: 1.5.2
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /health
                port: &port 6767
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
        resources:
          requests:
            cpu: 15m
            memory: 256Mi
          limits:
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL

service:
  app:
    ports:
      http:
        port: *port

persistence:
  config:
    existingClaim: local-bazarr-pvc
  media:
    existingClaim: local-media-pvc
    globalMounts:
      - path: /data/library

ingress:
  app:
    enabled: true
    className: ingress-nginx-media
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
    hosts:
      - host: bazarr.otohgunga.nl
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - secretName: bazarr-https-tls
        hosts:
          - bazarr.otohgunga.nl
