apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-bazarr-pv
  labels:
    app.kubernetes.io/name: bazarr
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local-bazarr
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/data/mediaserver/bazarr"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-home
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-bazarr-pvc
  namespace: media
  labels:
    app.kubernetes.io/name: bazarr
spec:
  storageClassName: local-bazarr
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
